### ISSUE TITLE
[FEATURE]-Add Command Passthru to Bridge Joinmap

### ISSUE THREAD

**Issue by cdenig** [PepperDash/epi-videoCodec-ciscoExtended#16]
**Is your feature request related to a problem? Please describe.**
I was hoping to be able to send custom commands and receive feedback responses from the codec, but found this not currently possible.  There is currently a signal to transmit commands to the EPI via the bridge (no delimiter), but there is no such response signal.

**Describe the solution you'd like**
Complete the existing CommandPassThru_Tx with a _Rx join on the bridge joinmap.  Would prefer that all received commands be sent over the bridge in their original form, i.e. not stripping the /x0d/x0A delimiter.

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by TrevorPayne** [comment]
No need for this - just bridge the extant communcations channel into your code if you want this.

Closing.
